server:
  port: 8888

logging:
  level:
    ROOT: DEBUG
    org.spring.framework.cloud.config: DEBUG

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/owermaiden/config-server-repo
          default-label: main
          clone-on-start: true
    fail-fast: true

